# Generated by Django 4.2.23 on 2025-07-03 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('country_of_origin', models.CharField(max_length=100)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('added_data', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dodany_przez', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
