# Generated by Django 4.2.25 on 2025-10-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_shoppinglistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.PositiveSmallIntegerField(unique=True)),
                ('d1_mm', models.FloatField(blank=True, null=True)),
                ('d2_mm', models.FloatField(blank=True, null=True)),
                ('distance_mm', models.FloatField(blank=True, null=True)),
                ('weight_g', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
