# Generated by Django 4.2.25 on 2025-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_shelfstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
