# Generated by Django 4.2.25 on 2025-10-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_product_shelf_number_alter_product_country_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='shelfstate',
            name='distance_mm',
        ),
    ]
